/**
 * Isolated Executor — the arm that touches the disk.
 *
 * These tests deliberately run real processes. A timeout, a kill and an
 * output cap are claims about operating-system behaviour, and a mock proves
 * nothing about any of them. They are slower than the rest of the suite and
 * that is the cost of the claim being true.
 *
 * Misbehaving workers live in fixtures generated by the test itself and are
 * injected via the workerPath option. No test hook exists in the production
 * worker, because a test hook in the isolated binary is a way to reach the
 * isolated path from the agent — which is the one thing isolation is for.
 */
import { mkdtemp, mkdir, writeFile, readFile, symlink, rm, realpath } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { IsolatedExecutor, resolveConfined } from "../.test-build-workspace/isolated-executor.js";

let pass = 0;
let fail = 0;
const check = (name, condition, detail = "") => {
  if (condition) {
    pass += 1;
    console.log(`  \x1b[32m✓\x1b[0m ${name}`);
  } else {
    fail += 1;
    console.log(`  \x1b[31m✗\x1b[0m ${name} ${detail}`);
  }
};

const root = await mkdtemp(join(tmpdir(), "executor-"));
const fixtures = join(root, "fixtures");
const workspace = join(root, "workspace");
const outside = join(root, "outside");
await mkdir(workspace, { recursive: true });
await mkdir(outside, { recursive: true });
await writeFile(join(outside, "secret.txt"), "TOP SECRET", "utf8");

// The fixture workers are generated by the test, not checked in.
const here = new URL(".", import.meta.url).pathname;
execFileSync(process.execPath, [join(here, "fixtures/make-worker-fixtures.mjs"), fixtures], { stdio: "pipe" });

const skill = {
  name: "note-taker",
  risk_level: "low",
  allowed_tools: ["write_file", "read_file"],
  allowed_directories: [workspace],
};

const worker = (name) => new IsolatedExecutor({ workerPath: join(fixtures, name) });

// ── real writes through the real worker ────────────────────────────────────
console.log("\n\x1b[1mthe real worker, writing for real\x1b[0m");

// The real worker lives in the app, three levels up from packages/ui/test.
// Resolved rather than hard-coded, so moving either side does not silently
// point the tests at nothing — which is what happened first.
const realWorkerPath = resolve(here, "../../../apps/command-center/app/lib/tools/worker.mjs");
const real = new IsolatedExecutor({ workerPath: realWorkerPath });

{
  const target = join(workspace, "note.md");
  const outcome = await real.run("write_file", { path: target, content: "hello" }, skill);

  check("a write reports success", outcome.ok === true, JSON.stringify(outcome.failure ?? outcome.error));
  check("the file exists on disk afterwards", (await readFile(target, "utf8")) === "hello");
  check("the reported path is the real one", outcome.path === await realpath(target));
  check("the previous contents were captured for undo", outcome.existed === false);
  check("an undo record is held", real.pendingUndos >= 1, `${real.pendingUndos}`);
}

{
  const target = join(workspace, "note.md");
  const again = await real.run("write_file", { path: target, content: "replaced" }, skill);
  check("overwriting an existing file reports the prior contents", again.previous === "hello", String(again.previous));
  check("and the file now holds the new text", (await readFile(target, "utf8")) === "replaced");
}

{
  const outcome = await real.run("read_file", { path: join(workspace, "note.md") }, skill);
  check("a read returns the file", outcome.ok === true);
  check("with the right contents",
    outcome.result?.content === "replaced", JSON.stringify(outcome.result));
}

{
  // A payload the worker cannot satisfy is a refusal from the tool, not a
  // crash of the supervisor. The distinction decides whether the pipeline
  // rolls back.
  const outcome = await real.run("write_file", { path: join(workspace, "x"), content: 42 }, skill);
  check("a malformed payload is refused by the tool", outcome.ok === false);
  check("classified as a refusal, not a crash", outcome.failure?.kind === "rejected", outcome.failure?.kind);
}

// ── rollback ───────────────────────────────────────────────────────────────
console.log("\n\x1b[1mrollback\x1b[0m");

{
  const target = join(workspace, "undo-me.md");
  const before = "original text";
  await writeFile(target, before, "utf8");

  await real.run("write_file", { path: target, content: "clobbered" }, skill);
  const heldBefore = real.pendingUndos;
  check("the file is clobbered before the undo", (await readFile(target, "utf8")) === "clobbered");

  await real.rollback({ payload: { path: target }, skill });
  check("rollback restores the prior contents", (await readFile(target, "utf8")) === before);
  // pendingUndos counts every held record, not this one specifically. An
  // earlier write in this suite still holds its own undo material, so the
  // meaningful assertion is that the count fell by one.
  check("and releases the undo record for that path", real.pendingUndos === heldBefore - 1,
    `${real.pendingUndos} vs ${heldBefore - 1}`);
}

{
  const target = join(workspace, "brand-new.md");
  await real.run("write_file", { path: target, content: "new" }, skill);
  await real.rollback({ payload: { path: target }, skill });
  let gone = false;
  try {
    await readFile(target, "utf8");
  } catch {
    gone = true;
  }
  check("rollback removes a file that did not previously exist", gone);
}

{
  // Commit is what keeps a long-lived agent from hoarding undo material for
  // writes nobody ever questioned.
  const target = join(workspace, "committed.md");
  await real.run("write_file", { path: target, content: "kept" }, skill);
  const held = real.pendingUndos;
  real.commit({ payload: { path: target } });
  check("commit releases the undo record", real.pendingUndos === held - 1, `${real.pendingUndos} vs ${held}`);
  check("and the file is left alone", (await readFile(target, "utf8")) === "kept");
}

// ── symlink confinement: the escape the authority could not see ────────────
console.log("\n\x1b[1msymlink confinement\x1b[0m");

// Declared out here so the cases below can each refer to the same escape
// without each block building its own — and so a stale link from an earlier
// block cannot be mistaken for the one under test.
const link = join(workspace, "escape");
await symlink(outside, link, "dir");

{

  /* The authority's check is lexical, and it would pass this: the path is
     inside the workspace by every string test. Only resolving the real path
     reveals that it leaves. This is the exact limitation the authority
     documents, and closing it is the executor's reason to exist. */
  const outcome = await real.run("write_file", { path: join(link, "secret.txt"), content: "owned" }, skill);
  check("a write through a symlink out of the workspace is refused", outcome.ok === false, JSON.stringify(outcome));
  check("classified as a refusal", outcome.failure?.kind === "refused", outcome.failure?.kind);
  check("and the real file outside is untouched", (await readFile(join(outside, "secret.txt"), "utf8")) === "TOP SECRET");
}

{
  const confined = await resolveConfined(join(link, "secret.txt"), [workspace]);
  check("resolveConfined names the escape", confined.ok === false);
  check("showing where it actually lands",
    confined.ok === false && confined.reason.includes(outside), confined.reason);
}

{
  // The file need not exist: creation is the case where the escape would be
  // invisible, since there is nothing yet to inspect.
  const deep = join(workspace, "not", "yet", "made.md");
  const confined = await resolveConfined(deep, [workspace]);
  check("a not-yet-existing file inside the workspace resolves", confined.ok === true, JSON.stringify(confined));
  check("and resolves to the real location", confined.ok === true && confined.real === deep);
}

{
  // A symlinked root is resolved too, so declaring it does not create a
  // second way out.
  const linkRoot = join(root, "root-link");
  await symlink(workspace, linkRoot, "dir");
  const inside = await resolveConfined(join(linkRoot, "ok.md"), [linkRoot]);
  check("a symlinked allowed root still resolves to a contained real path",
    inside.ok === true && inside.real.startsWith(await realpath(workspace)), JSON.stringify(inside));
}

{
  const confined = await resolveConfined(join(workspace, "x"), []);
  check("no allowed directories means no path is confined", confined.ok === false);
  const missing = await resolveConfined(join(workspace, "x"), [join(root, "does-not-exist")]);
  check("an allowed directory that does not exist is refused", missing.ok === false);
}

// ── hard timeout ───────────────────────────────────────────────────────────
console.log("\n\x1b[1mhard timeout\x1b[0m");

{
  const hang = new IsolatedExecutor({
    workerPath: join(fixtures, "hang-worker.mjs"),
    defaultTimeoutMs: 400,
  });
  const started = Date.now();
  const outcome = await hang.run("write_file", { path: join(workspace, "never.md"), content: "x" }, skill);
  const elapsed = Date.now() - started;

  check("a hung child is stopped", outcome.ok === false);
  check("reported as a timeout", outcome.failure?.kind === "timeout", outcome.failure?.kind);
  check("it really was killed rather than waited out", elapsed < 3000, `${elapsed}ms`);
  check("and the reason names the budget", /budget/.test(outcome.failure?.reason ?? ""));
}

{
  // SIGTERM would be a request. A wedged process can decline it, which is
  // the entire reason the kill is SIGKILL.
  const stubborn = new IsolatedExecutor({
    workerPath: join(fixtures, "stubborn-worker.mjs"),
    defaultTimeoutMs: 400,
  });
  const started = Date.now();
  const outcome = await stubborn.run("write_file", { path: join(workspace, "never.md"), content: "x" }, skill);
  const elapsed = Date.now() - started;

  check("a child that ignores SIGTERM is still killed", outcome.ok === false, JSON.stringify(outcome));
  check("reported as a timeout, not a hang", outcome.failure?.kind === "timeout", outcome.failure?.kind);
  check("promptly", elapsed < 3000, `${elapsed}ms`);
}

{
  const slow = new IsolatedExecutor({ workerPath: join(fixtures, "hang-worker.mjs") });
  const outcome = await slow.run(
    "write_file",
    { path: join(workspace, "never.md"), content: "x" },
    { ...skill, timeout_ms: 300 },
  );
  check("a skill's own timeout is honoured", outcome.failure?.kind === "timeout", outcome.failure?.kind);
}

// ── output quota ───────────────────────────────────────────────────────────
console.log("\n\x1b[1moutput quota\x1b[0m");

{
  // Buffering without a cap is a denial of service: a printing loop
  // exhausts memory in bytes long before any timeout, which is in seconds,
  // gets around to firing.
  const flood = new IsolatedExecutor({
    workerPath: join(fixtures, "flood-worker.mjs"),
    defaultTimeoutMs: 5000,
    maxOutputBytes: 64 * 1024,
  });
  const started = Date.now();
  const outcome = await flood.run("write_file", { path: join(workspace, "x"), content: "x" }, skill);
  const elapsed = Date.now() - started;

  check("a flooding child is stopped", outcome.ok === false);
  check("reported as an output limit", outcome.failure?.kind === "output_limit", outcome.failure?.kind);
  check("killed long before the timeout would have fired", elapsed < 5000, `${elapsed}ms`);
}

{
  // The cap has to be a boundary, not a blanket "no output allowed".
  const chatty = new IsolatedExecutor({
    workerPath: join(fixtures, "chatty-worker.mjs"),
    maxOutputBytes: 64 * 1024,
  });
  const outcome = await chatty.run("write_file", { path: join(workspace, "x"), content: "x" }, skill);
  check("output under the cap is accepted", outcome.ok === true, JSON.stringify(outcome.failure));
  check("and the result is still parsed", outcome.result?.result === "verbose");
}

{
  // The other side of the same coin. Reading the last parseable line would
  // make a half-written answer look like the complete one printed before it,
  // which is the worst possible reading: a plausible success that is not true.
  const truncated = worker("truncated-worker.mjs");
  const outcome = await truncated.run("write_file", { path: join(workspace, "x"), content: "x" }, skill);
  check("a truncated final result is not read as the one before it", outcome.ok === false, JSON.stringify(outcome));
  check("it is a protocol failure", outcome.failure?.kind === "protocol", outcome.failure?.kind);
  check("and no result is invented from the earlier complete line", outcome.result === undefined);
}

// ── a child that dies, or says nothing ─────────────────────────────────────
console.log("\n\x1b[1ma child that dies or says nothing\x1b[0m");

{
  const crash = worker("crash-worker.mjs");
  const outcome = await crash.run("write_file", { path: join(workspace, "x"), content: "x" }, skill);
  check("a crashing child does not report success", outcome.ok === false, JSON.stringify(outcome));
  check("it is reported as a crash", ["crash", "protocol"].includes(outcome.failure?.kind), outcome.failure?.kind);
}

{
  // Exit code 0 with no output is the trap. A tool that wrote nothing and a
  // tool that never ran look identical to a supervisor that trusts the exit
  // code, and the difference is the whole point of verifying.
  const silent = worker("silent-worker.mjs");
  const outcome = await silent.run("write_file", { path: join(workspace, "x"), content: "x" }, skill);
  check("a silent success is not accepted as success", outcome.ok === false, JSON.stringify(outcome));
  check("it is reported as a protocol failure", outcome.failure?.kind === "protocol", outcome.failure?.kind);
}

{
  const garbage = worker("garbage-worker.mjs");
  const outcome = await garbage.run("write_file", { path: join(workspace, "x"), content: "x" }, skill);
  check("unparseable output is a protocol failure", outcome.failure?.kind === "protocol", outcome.failure?.kind);
  check("and is not trusted", outcome.ok === false);
}

{
  const refusing = worker("refusing-worker.mjs");
  const outcome = await refusing.run("write_file", { path: join(workspace, "x"), content: "x" }, skill);
  check("a tool that refuses in its own terms is a refusal", outcome.failure?.kind === "rejected", outcome.failure?.kind);
  check("and its reason is carried through", outcome.error === "disk is full", outcome.error);
}

// ── the ordinary path still works ──────────────────────────────────────────
console.log("\n\x1b[1nthe ordinary path\x1b[0m");

{
  const ok = worker("ok-worker.mjs");
  const outcome = await ok.run("write_file", { path: join(workspace, "x"), content: "x" }, skill);
  check("a well-behaved child reports success", outcome.ok === true, JSON.stringify(outcome));
  check("with no failure attached", outcome.failure === undefined);
}

// ── the environment boundary ──────────────────────────────────────────────
/*
 * A capability surface says what a task may do. It says nothing about what
 * the process holds, and those are different attacks.
 *
 * With `env: { ...process.env }`, a task granted nothing but workspace.write
 * still received every variable in the server's environment. If an OAuth
 * token was in there, the surface was decorative: the child could not have
 * been asked to use the token, it simply already had it.
 *
 * These assertions observe the environment from inside the child, because
 * that is the only place the boundary actually exists.
 */
console.log("\n\x1b[1mthe child gets a constructed environment, not an inherited one\x1b[0m");

/* Put something unmistakably secret-shaped into the server's own environment
   first. Without this the test would pass for the wrong reason: a parent
   with a clean environment has nothing to leak, so the assertion would be
   measuring the absence of secrets in the test runner rather than the
   absence of inheritance in the child. */
const PLANTED = {
  GOOGLE_OAUTH_TOKEN: "ya29.planted-master-token",
  AWS_SECRET_ACCESS_KEY: "planted-secret-key",
  DB_PASSWORD: "planted-password",
  MASTER_CREDENTIAL: "planted-credential",
};
Object.assign(process.env, PLANTED);

{
  const dumper = new IsolatedExecutor({ workerPath: join(fixtures, "env-dump-worker.mjs") });
  const outcome = await dumper.run("env_dump", {}, skill);
  check("the env-dumping worker ran", outcome.ok === true, JSON.stringify(outcome.failure));

  const seen = outcome.result?.keys ?? [];
  const values = outcome.result?.values ?? {};

  // Each planted secret, checked by value and not merely by name: a variable
  // renamed on the way through would be just as much of a leak.
  for (const [name, value] of Object.entries(PLANTED)) {
    check(`"${name}" did not reach the child`, seen.includes(name) === false, seen.join(","));
    check(`and its value is not present under any name`,
      Object.values(values).includes(value) === false, JSON.stringify(seen));
  }

  check("no value from the server environment is present at all",
    Object.keys(PLANTED).some((k) => seen.includes(k)) === false, seen.join(","));

  /* Small and explicit, rather than merely free of the planted names. A
     deny-list of secret-shaped keys would pass this test while missing any
     secret with an unusual name, so the bound is on the whole set. */
  check("the child's environment is small", seen.length <= 4, `${seen.length}: ${seen.join(",")}`);

  // The floor for running at all, present for the right reason.
  check("PATH is there so a tool can find a binary", typeof values.PATH === "string");
  check("NODE_ENV is there as a behaviour switch", values.NODE_ENV === "production");
}

{
  // Inheritance is gone, so anything a worker genuinely needs has to be
  // granted by name. This is the property that makes the above a boundary
  // rather than a filter.
  const withGrant = new IsolatedExecutor({
    workerPath: join(fixtures, "env-dump-worker.mjs"),
    taskEnv: { CELESTYLE_TASK_REGION: "eu-central-1" },
  });
  const outcome = await withGrant.run("env_dump", {}, skill);
  const values = outcome.result?.values ?? {};

  check("an explicitly granted variable reaches the child",
    values.CELESTYLE_TASK_REGION === "eu-central-1", JSON.stringify(values));
  check("and granting one does not open the rest",
    Object.keys(PLANTED).some((k) => outcome.result?.keys?.includes(k)) === false);
  check("the environment stays small", outcome.result?.keys?.length <= 5,
    String(outcome.result?.keys?.length));
}

{
  /* The boundary is visible without spawning anything, so a leak can be
     checked by inspection rather than only by running a process. */
  const described = new IsolatedExecutor({ taskEnv: { CELASTYLE_TASK_ID: "t-1" } }).describeEnv();
  const keys = Object.keys(described);

  check("describeEnv lists only the constructed keys",
    keys.includes("NODE_ENV") && keys.includes("PATH") && keys.includes("CELASTYLE_TASK_ID"),
    keys.join(","));
  check("and nothing from the server environment appears",
    Object.keys(PLANTED).some((k) => keys.includes(k)) === false, keys.join(","));

  /* A replacement, not a merge. Merging would keep every key already
     granted, which is how a variable granted for one capability quietly
     outlives it and becomes ambient authority again. */
  const executor = new IsolatedExecutor({ taskEnv: { FIRST: "1", SECOND: "2" } });
  executor.setTaskEnv({ THIRD: "3" });
  const after = executor.describeEnv();
  check("setTaskEnv replaces rather than merges",
    after.FIRST === undefined && after.SECOND === undefined && after.THIRD === "3",
    JSON.stringify(after));
}

{
  // The planted variables must not reach anything else either. A test that
  // leaves secrets in the runner's environment poisons every later suite.
  for (const key of Object.keys(PLANTED)) delete process.env[key];
  check("the planted secrets are cleaned up", Object.keys(PLANTED).some((k) => k in process.env) === false);
}

await rm(root, { recursive: true, force: true });

console.log(`\n${fail === 0 ? "\x1b[32m✅" : "\x1b[31m❌"} ${pass} passed, ${fail} failed\n`);

console.log(`\n${fail === 0 ? "\x1b[32m✅" : "\x1b[31m❌"} ${pass} passed, ${fail} failed\n`);
process.exit(fail === 0 ? 0 : 1);
